### Linear Algebra
As linear albebra is really important in computer science and machine learning, so this is a tutorial for linear algebra, as the math that we could use in machine learning we don't need to much math in fact, but the linear algegra is the most important and fundamental operations that we could use!
So here I write one tutorial for the basic linear algebra tutorial also with some python code and some Chinese comments for the name that we could use.

Here we start!

In [67]:
# we just use the numpy module for explain
import numpy as np

# a tip: we would use the numpy module, np.linalg.   (linalg of numpy module mean linear algebra)

In [2]:
# as linear algebra is used to solve the one-varaible function like this:
# 4x1 − 5x2 = −13
# −2x1 + 3x2 = 9.
# we could extract the content variable and X and result to matrix to reprensent it: AX = b
A = np.matrix(np.array([[4, -5], [-2, 3]]))
b = np.matrix(np.array([-13, 9]))

# matrix is really similiar to np.ndarray, but some with some more useful properties

In [5]:
# first is to get the shape of matrix, just as np.ndarray
# tips: computer would store matrix or array with column
print("A shape:", A.shape)
# so A belongs to R(2, 2); 2 as rows and 2 as columns
print("b shape:", b.shape)
# b belongs to R(1, 2)  

A shape: (2, 2)
b shape: (1, 2)


### Matrix multiplication

Matrix multiplication is most useful in the computer science! you could reference with the multiply with our previous explain in papers!

One important thing is: np.dot(A, B), where A (- (m, n) and B (- (n, t)!   A's columns must equal to B's rows! otherwise, two matrix couldn't be multiplied!

In [7]:
# example for dot product: 向量内积
A = np.matrix(np.random.randn(4, 5))
B = np.matrix(np.random.randn(5, 2))

print("result:", np.dot(A, B))    

result: [[ 7.1506582  -4.18467223]
 [ 3.210101   -1.28557004]
 [-1.49054211  1.04165342]
 [ 0.10695623  0.41318964]]


In [29]:
# here is more readable example 
# this is matrix * matrix
data = np.matrix(np.arange(1, 5).reshape(2, -1)) 
# -1 means we don't know how much columns, but in fact we know that it is 2 * 2, but we also could do this
data

matrix([[1, 2],
        [3, 4]])

In [9]:
print("data dot product with data: ", np.dot(data, data))
# result is computed with 1th row, 1th column: 1 * 1 + 2 * 3 = 7; 1th row 2th column: 1 * 2 + 2 * 4 = 10
# others you could compute with yourself

data dot product with data:  [[ 7 10]
 [15 22]]


In [14]:
# matrix * vector
data_vector = np.matrix(b.reshape(2, -1))
print("vector shape:", data_vector.shape)

res = np.dot(data, data_vector)
print("matrix * vector:", res)

print("data shape:", data.shape)
print("vector is:", data_vector.shape)
print("matrix * vector shape:", res.shape)

vector shape: (2, 1)
matrix * vector: [[ 5]
 [-3]]
data shape: (2, 2)
vector is: (2, 1)
matrix * vector shape: (2, 1)


In [18]:
# vector * vector
data_vector_left = np.matrix(b.reshape(-1, 2)) # 1*2
data_vector_right = np.matrix(b.reshape(2, -1)) # 2*1

res = np.dot(data_vector_left, data_vector_right)

print("left shape:", data_vector_left.shape)
print("right shape:", data_vector_right.shape)
print("result shape:", res.shape)
print("result is:",res)   # just one value

left shape: (1, 2)
right shape: (2, 1)
result shape: (1, 1)
result is: [[250]]


#### Important property

Here is some important property that should know for linear algebra! Also with comments.

In [22]:
# 1. Identity matrix （单位阵，全部为1）
# identity matrix with any matrix multiply will result same matrix!
iden_matrix = np.matrix(np.ones((4, 3)))
print("Identity matrix shape:", iden_matrix.shape)
iden_matrix

Identity matrix shape: (4, 3)


matrix([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [24]:
# 2. Diagonal matrix （对角阵: 对角线有值，其他为0）
dia_matrix = np.matrix(np.diag([1, 2, 3]))
dia_matrix

matrix([[1, 0, 0],
        [0, 2, 0],
        [0, 0, 3]])

In [31]:
# 3. Transpose （转置， 对角线位置不变，其他位置对应替换）
print('original:', data)
print('transpose:', data.T)

original: [[1 2]
 [3 4]]
transpose: [[1 3]
 [2 4]]


In [38]:
# 3.1 transpose property
A = np.matrix(np.random.randn(4, 3))
B = np.matrix(np.random.randn(3, 2))

# (A.T).T = A
print("(A.T).T = A:", np.allclose(A.T.T, A))

# (A * B).T = B.T * A.T
print("(A * B).T = B.T * A.T: ", np.allclose(np.dot(A, B).T, np.dot(B.T, A.T) ))

# (A + B).T = A.T + B.T
print("(A + B).T = A.T + B.T: ", np.allclose((A + A).T, A.T + A.T))

(A.T).T = A: True
(A * B).T = B.T * A.T:  True
(A + B).T = A.T + B.T:  True


In [42]:
# 4. Trace （迹， 对角线值的和）
print("original matrix:", data)

print("trace of matrix data:", np.trace(data))  # with 1 + 4 = 5

original matrix: [[1 2]
 [3 4]]
trace of matrix data: 5


In [51]:
# 4.1 trace property
A = np.matrix(np.random.randn(4, 4))
B = np.matrix(np.random.randn(4, 4))  # another matrix with same shape of A, but with different value, you could check

# trace(A) = trace(A.T)
print("trace(A) = trace(A.T):", np.trace(data) == np.trace(data.T))

# trace(A + B) = trace(A) + trace(B)
print("trace(A + B) = trace(A) + trace(B): ", np.allclose(np.trace(A + B), np.trace(A) + np.trace(B)))

# trace(t*A) = t* trace(A), t is just a constant number
print("trace(t*A) = t* trace(A): ", np.allclose(np.trace(3 * A), 3 * np.trace(A)))

# trace(A * B) = trace(B * A), s.t. A, B are square matrix
print("trace(A * B) = trace(B * A): ", np.allclose(np.trace(np.dot(A, B)), np.trace(np.dot(B, A))))

trace(A) = trace(A.T): True
trace(A + B) = trace(A) + trace(B):  True
trace(t*A) = t* trace(A):  True
trace(A * B) = trace(B * A):  True


In [57]:
# 5. Norm (中文定量？ 主要用来求距离, 中学的欧式距离), norm seperate 3 classes；l1-norm, l2-norm(Euclidean distance) and lp-norm, 
# the function to compute the norm of l2 is: np.sqrt(np.sum(x)), norm is used to compute the distance with (vector)!
print("org vector:", data_vector)
print("L1 norm of A:", np.linalg.norm(data_vector, ord=1))  # |-13| + |9| = 22
print("L2 norm of A:", np.linalg.norm(data_vector, ord=2))  # np.sqrt((-13)**2 + (9)**2 ) 

org vector: [[-13]
 [  9]]
L1 norm of A: 22.0
L2 norm of A: 15.811388300841896


In [61]:
# 5.1. Norm property

# norm is must uppper to 0
print("norm is upper to 0:", np.linalg.norm(data_vector) > 0)

# t * norm(x) == norm(t * x)
print("t * norm(x) == norm(t * x): ", np.allclose(3 * np.linalg.norm(data_vector), np.linalg.norm(3 * data_vector)))

# norm(x + y) <= norm(x) + norm(y)
print("norm(x + y) <= norm(x) + norm(y): ", np.linalg.norm(data_vector + data_vector) <= np.linalg.norm(data_vector) + np.linalg.norm(data_vector))

norm is upper to 0: True
t * norm(x) == norm(t * x):  True
norm(x + y) <= norm(x) + norm(y):  True


In [62]:
# 6. Linear independent (线性独立, dependent：相关的意思，独立就是互相没有影响，相关就是说一个向量可以用其他向量线性相加得到) 
# Assume you have n vectors {x1, x2, ... xn} (- (m), these vectors are same dimension with mD(D means dimension), linear depement
# means that one vector could be computed with others vector sum with weights, like this: xn = a1*x1 + a2*x2+ ..+an*xn (a1, a2 ..an) 
# is weights are some content variable. like x1 = [1, 2], x2 = [2, 3], x3 = [4, 7], so x3 = 2*x1 + x2
# Linear independent means that we couldn't find the weights to compute one vector with others sum with weights. Linear dependent
# could be used to compute the linear function like  AX = b, AS A is matrix(matrix are just some vectors combined), b is a vector,
# so A's vector and b also a vector, they are dependent when x could be computed, otherwise they are independent.
# Noted: not all linear function has solution, like this: {x1 + 2*x2 = 1, 2*x2 + 4 * x2 = 2} this we couldn't find one
# unique solution for this function, as they are dependent with each other(second function = first function * 2)

In [64]:
# 7. Rank （矩阵的秩[zhi四声]）
# matrix A (- (m, n) m rows and n columns. column rank is the number that subset of columns of A that are independent with each
# other(now matrix A is compressed with columns for n columns); row rank is the number of subset of rows of A that are 
# independent with each other(m rows). 
# Noted: given any matrix A, column rank is same with row rank  (you could think with Transpose of A, row rank of A is the 
# column rank of A.T), you could just know this property.


# here we just to compute the rank of matrix
print("Matrix is: ", A)

print("Rank of A is : ", np.linalg.matrix_rank(A))

Matrix is:  [[ 1.54857288  0.72267192 -0.31090072 -0.07399397]
 [ 1.70813862  0.46655917  1.06191653 -2.51648034]
 [ 1.49626721 -1.09170817  1.73840425 -0.77898378]
 [-0.25234205 -0.73771393  0.42080921  0.36295027]]
Rank of A is :  4


In [66]:
# 7.1 Rank property

# rank(A) <= min(m, n)  min means 两个值中的最小的那个, 
# important:  if rank(A) = min(m, n), then A is full rank (满秩)！！！！

print("min function test to get the min : ", min(4, 3))

print("rank(A) <= min(m, n): ", np.linalg.matrix_rank(A) <= min(A.shape))   # get the shape of A as (m, n), m rows and n columns

# rank(A) = rank(A.T)
print("rank(A) = rank(A.T): ", np.linalg.matrix_rank(A) == np.linalg.matrix_rank(A.T))

# rank(A * B) <= min(Rank(A), Rank(B))
A = np.matrix(np.random.randn(4, 4))
B = np.matrix(np.random.randn(4, 4))
print("rank(A * B) <= min(Rank(A), Rank(B)): ", 
      np.linalg.matrix_rank(np.dot(A, B)) <= min(np.linalg.matrix_rank(A), np.linalg.matrix_rank(B)))

# rank(A + B) <= rank(A) + rank(B)
print("rank(A + B) <= rank(A) + rank(B): ", np.linalg.matrix_rank(A + B) <= np.linalg.matrix_rank(A) + np.linalg.matrix_rank(B))

min function test to get the min :  3
rank(A) <= min(m, n):  True
rank(A) = rank(A.T):  True
rank(A * B) <= min(Rank(A), Rank(B)):  True
rank(A + B) <= rank(A) + rank(B):  True


In [69]:
# 8. Inverse (矩阵的逆)
# matrix inverse is important but easy to understand!!! How to represent the inverse is: A-1
# inverse property:  A * A-1 == I == A-1 * A !!!! Another important tip: A must be square matrix as A (- (n, n) rows = columns
# But even for square matrix, doesn't means that it will have inverse matrix, 
# so if A has A-1, then called A is non-singular(非奇异的)
# if A doesn't have A-1, then A is called singular (奇异的).

# here to compute the inverse of matrix A
print('original matrix: ', A)

print('inverse of matrix: ', A.I)  # I means inverse

print("dot product of A and A-1, should be identity matrix: ", np.dot(A, A.I))  
# e-10 means 0.0000000001 (-10 means 0.十个0) 非常小，可以忽略不计，所以是一个对角为1，其他为0的对角阵


original matrix:  [[ 0.14594637 -0.38210768  0.12607345  3.16021619]
 [-0.72209548  0.13631996 -0.12496719  0.68497759]
 [-3.06052343  0.25301834 -1.25486347 -1.90082792]
 [ 0.95958359 -1.23599602 -1.65887101  2.04606418]]
inverse of matrix:  [[-0.83586385  1.35056268 -0.5957664   0.28540449]
 [-2.79208208  6.9367809  -1.61672528  0.48821881]
 [ 1.54243638 -3.26881379  0.62218241 -0.71000048]
 [-0.04409349  0.90677282 -0.19278867  0.0741755 ]]
dot product of A and A-1, should be identity matrix:  [[ 1.00000000e+00  8.08639401e-16 -2.82567118e-17  1.32246867e-16]
 [-4.39023462e-19  1.00000000e+00 -4.93113407e-17 -4.18599180e-19]
 [-7.15431503e-20 -7.75960340e-17  1.00000000e+00  1.52393716e-17]
 [-1.12953535e-16  3.40819075e-16 -4.43471226e-18  1.00000000e+00]]


In [71]:
# 8.1 inverse property

# A.I.I = A
print("A.I.I = A: ", np.allclose(A.I.I, A))

# (A*B).I = B.I * A.I
print("(A*B).I = B.I * A.I: ", np.allclose(np.dot(A, B).I, np.dot(B.I, A.I)))

# A.I.T = A.T.I   # means A的转置的逆 = A的逆的转置
print("A.I.T = A.T.I:", np.allclose(A.I.T, A.T.I))

A.I.I = A:  True
(A*B).I = B.I * A.I:  True
A.I.T = A.T.I: True


In [72]:
# 9. Orthogonal matrix (正交阵, 正交means向量夹角为90度，如x, y, z三维坐标)
# x, y is nD(dimension) vector, if x*y = 0, then x, y are orthogonal! like (1, 0) * (0, 1) = 0
# if A (- (N, N) is square matrix if and only if A's whole columns are orthogonal with each other.
# diagonal matrix is a orthogonal matrix:
print("diagonal matrix is a orthogonal matrix: ", np.matrix(np.diag([1, 2, 3])))

diagonal matrix is a orthogonal matrix:  [[1 0 0]
 [0 2 0]
 [0 0 3]]


In [73]:
# 9.1 orthogonal matrix property
# if A is orthogonal matrix and A is normalized, then A * A.T = I = A.T * A
diag_matrix = np.matrix(np.diag([1, 2, 3]))
print("A * A.T = I = A.T * A: ", np.allclose(np.dot(diag_matrix , diag_matrix.T), np.dot(diag_matrix.T, diag_matrix)))

print("A * A.T is: ", np.dot(diag_matrix , diag_matrix.T))

A * A.T = I = A.T * A:  True
A * A.T is:  [[1 0 0]
 [0 4 0]
 [0 0 9]]


In [75]:
# 10. Determinant （行列式）
# The determinant of a squared matrix A means the volume of the matrix, a little tip: if the matrix is A is singular, then the 
# determinant of the matrix is 0!

print("Origin data: ", A)

print("Determinant of matrix is: ", np.linalg.det(A))

Origin data:  [[ 0.14594637 -0.38210768  0.12607345  3.16021619]
 [-0.72209548  0.13631996 -0.12496719  0.68497759]
 [-3.06052343  0.25301834 -1.25486347 -1.90082792]
 [ 0.95958359 -1.23599602 -1.65887101  2.04606418]]
Determinant of matrix is:  2.8218299972245084


In [87]:
# 10.1 Determinant property

# identity matrix determinant is 1
identity_matrix = np.matrix(np.diag([1, 1, 1]))
print("identity_matrix: ", identity_matrix)
print("identity matrix determinant: ", np.linalg.det(identity_matrix))

singular_matrix = iden_matrix[:2, :2]
print("Singular_matrix is: ", singular_matrix)
print("Singular matrix determinant should be zero: ", np.linalg.det(singular_matrix))

# det(A) = det(A.T)
print("det(A) = det(A.T): ", np.allclose(np.linalg.det(A), np.linalg.det(A.T)))

# det(A*B) = det(A) * det(B)
print("det(A*B) = det(A) * det(B): ", np.allclose(np.linalg.det(np.dot(A, B)), np.linalg.det(A) * np.linalg.det(B)))

# det(A.I) = 1/ det(A) if A is non-singular (columns are independent with each other)
print("det(A.I) = 1/ det(A) if A is non-singular: ", np.allclose(np.linalg.det(A.I), 1./ np.linalg.det(A) ))

identity_matrix:  [[1 0 0]
 [0 1 0]
 [0 0 1]]
identity matrix determinant:  1.0
Singular_matrix is:  [[1. 1.]
 [1. 1.]]
Singular matrix determinant should be zero:  0.0
det(A) = det(A.T):  True
det(A*B) = det(A) * det(B):  True
det(A.I) = 1/ det(A) if A is non-singular:  True


In [96]:
# 11. Eigen value and eigen vector (特征值及特征向量)
# for square matrix A (- (N, N), a is eigen value and x is eigen vector if A*X = a*X
# this definition means that multiplying A by the vector x results in a new vector
# that points in the same direction as x, but scaled by a factor λ. (if you don't understand this, I will show you)

# Here is to compute the eigen value and eigen vector
eigen_value, eigen_vector = np.linalg.eig(data)
print("Orig data: ", data)
print("Eigen value: ", eigen_value)
print("Eigen vector: ", eigen_vector)


Orig data:  [[1 2]
 [3 4]]
Eigen value:  [-0.37228132  5.37228132]
Eigen vector:  [[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]


In [107]:
# 11.1 eigen value and eigen vector property
# as eigen value and eigen vector is really important for some machine learning alogirithm to reduce the dimension of data,
# bellow property could be known.

# trace of matrix is sum of the eigen values
print("trace of matrix is sum of the eigen values: ", np.allclose(np.trace(data), np.sum(eigen_value)))

# determinant of matrix is product of eigen values, as det(A) = eigen_value[0] * eigen_value[1] * ...
# np.prod(eigen_value) is multiply with each variables
print("determinant of matrix is product of eigen values: ", np.allclose(np.linalg.det(data), np.prod(eigen_value) ))

# rank of matrix is number of non-zero of eigen value
print("non-zero value:",np.nonzero(eigen_value))
print("rank of matrix is number of non-zero of eigen value: ", np.rank(data) == len(np.nonzero(eigen_value)[0]))

trace of matrix is sum of the eigen values:  True
determinant of matrix is product of eigen values:  True
non-zero value: (array([0, 1], dtype=int64),)
rank of matrix is number of non-zero of eigen value:  True


C:\Users\Public\anaconda\lib\site-packages\ipykernel_launcher.py:14: VisibleDeprecationWarning: `rank` is deprecated; use the `ndim` attribute or function instead. To find the rank of a matrix see `numpy.linalg.matrix_rank`.
  
